### PR TITLE
Use Immutable data structures in messages reducer.

### PR DESCRIPTION
**Pull request by nchevobbe**
Basically, switch `state` from Array to Immutable.List.
Require immutable.js (already in the tree).
Fix tests that are affected by this change.

### CODE REVIEW

**Comment by nchevobbe** [comment]
@bgrins implementing console.clear would require me to modify 2 files already modified in this PR (reducers/messages.js and test/store/test_messages). Do you think you could review this, or should I add console.clear and rebase this PR after ?

**Comment by bgrins** [comment]
@nchevobbe Looks good to me

**Comment by nchevobbe** [comment]
@bgrins Are you talking about the PR ? if so, can you merge it please ? I don't have write access to this repo.

**Comment by bgrins** [comment]
Merged, thanks

**Pull request merged**
