### PR TITLE
Fix XPCShell when using shared head

### PR DESCRIPTION
**Pull request by linclark**
@bgrins this builds on your PR in #153. If it looks good to you, I'll squash my changes into your commit and land it.

### CODE REVIEW

**Comment by linclark** [comment]
It looks like this is still failing on try :(

@bgrins what do you think is the best option?

**Comment by linclark** [comment]
Scratch that, this may have failed for an entirely expected reason. Will report back soon....

**Comment by linclark** [comment]
Looks like try can't find the xpcshell head.

https://treeherder.mozilla.org/#/jobs?repo=try&revision=814181fa5f3f&selectedJob=24236439

I'm thinking the best solution (at least for now) is to have separate XPCShell heads. Anything that needs to be shared between those can be broken out into modules (which is probably useful anyway, because then we can require those modules across different kinds of tests).

**Comment by bgrins** [comment]
So should we make the test packet / ConsoleMessage data exported from a module in the test folder (using DevToolsModules in the moz.build)?

**Comment by linclark** [comment]
yeah, that's what I'm thinking.

**Comment by linclark** [comment]
Also, I think we could keep the unified Mochitest head file... unless you think that the inconsistency between a unified Mochitest head file and separate XPCShell head files would be confusing.

**Comment by bgrins** [comment]
That's fine with me

**Pull request closed without merging**
