### PR TITLE
Skip normal functionality if the new frontend is enabled

### PR DESCRIPTION
**Pull request by bgrins**
WIP

### CODE REVIEW

**Comment by bgrins** [comment]
This needs to be adjusted to emit 'new-messages' so that waitForMessages will still work

**Comment by bgrins** [comment]
This is probably needed for #25

**Comment by bgrins** [comment]
Note: There are a number of tests that do `outputNode.childNodes` but should really be doing something like `outputNode.querySelectorAll("message")` to play more nicely with this new code

**Comment by linclark** [comment]
@bgrins should we close this one out?

**Comment by bgrins** [comment]
Yes, filed #99 as a replacement for this, since this covered both skipping normal functionality (done) and making tests run (not done)

**Pull request closed without merging**
