### PR TITLE
Use ConsoleMessage and not packet data for repeatId

### LINKED ISSUE #147: Use ConsoleMessage for repeatId instead of packet data
This will make it easier to test things.

Types basically give us a defined message API. This means stubbing out message objects will be much more reliable. We can just have a set of tests which iterate through the stubs and make sure that `prepareMessage` returns the correct message.

However, the way we're handling `repeatId` makes stubbing out ConsoleMessage objects brittle. Instead, we should just be able to compare two objects to each other in the reducer.

### PR DESCRIPTION
**Pull request by linclark**
Fix #147

This makes testing easier.

### CODE REVIEW

**Comment by bgrins** [comment]
This'll need rebasing.  Also, is it ready for review?

**Comment by linclark** [comment]
I'm going to wait to move this to review until we land #153. The head stuff will move as part of that.

**Comment by linclark** [comment]
@bgrins this is ready for review

**Comment by bgrins** [comment]
r+, this is great

**Pull request merged**
