### PR TITLE
add locations with source-maps

### LINKED ISSUE #89: Add a file location component
Add a component which would display the file and line number the message is logged from
Clicking on the location should open the file in the debugger at the specified line

This component would be displayed at the end of each log message, and at the end of each stacktrace item  when console.trace() is called

### PR DESCRIPTION
**Pull request by jbhoosreddy**
Fixes #89. I pulled the latest code but does not merge for some reason. Will look into it tomorrow. Let me know if you have any suggestions. I'll take a look at the tests next.

### CODE REVIEW

**Comment by linclark** [comment]
Tested this out locally and it's working... niiiiiice! I can look into the merge issue.

**Comment by linclark** [comment]
This merge is going to be tough. Since you've now figured out exactly where things need to be changed, the easier path might be to check out today's `devtools-html/console-frontend` and apply the changes manually.

**Comment by jbhoosreddy** [comment]
Yes. I planned to make a subsequent PR, If you didn't have any follow up
suggestions. I'll make new one which can be merged.

**Comment by jbhoosreddy** [comment]
hey @linclark. can you check this out? also let me know what the next steps should be?

**Comment by linclark** [comment]
I can check this out on Monday. Quick question, is this now based on the most recent console-frontend?

**Comment by jbhoosreddy** [comment]
Yes. I pulled from the latest at the time, and I don't believe there's any merge conflicts now.

**Comment by linclark** [comment]
Overall, this looks like the right direction.

When I `npm test` I get some errors. These seem to be when `frame` is null.

When I manually test it using `console.log` or `console.count`, the location is the string `debugger eval code`. This should be blank to match current behavior.

Feel free to ping if you have any questions.

**Comment by linclark** [comment]
FYI, fixing the `messageAdd` test is easy. You just need to add this to the stub:

```
      frame: {
        source: "file:///test.html",
        line: 1,
        column: 1,
      }
```

I'm planning to automate the creation/update of the stubs in #169. But for now, we have to manually update. 

There will still be an error after this, and I think it's likely a bug that needs to be tracked down.

**Comment by jbhoosreddy** [comment]
@linclark I followed up on the previous comments. let me know if you have any other suggestions regarding this.

**Comment by jbhoosreddy** [comment]
@linclark I modified the PR. It should work now. Let me know of any further steps I might need take.

**Comment by jbhoosreddy** [comment]
@linclark let me know if this is okay?

**Comment by linclark** [comment]
Sorry, I didn't realize you'd updated the PR since you messaged on IRC. This looks good! Thanks for helping out.

**Comment by nchevobbe** [comment]
@jbhoosreddy 👍

**Pull request merged**
