### PR TITLE
Add support for console.trace()

### LINKED ISSUE #66: Add support for console.trace()
- Testing string: 

```
data:text/html;charset=utf-8,<script>function foo() {console.trace()}; foo()</script>
```
- [HTML and packets](https://github.com/linclark/webconsole-rdp/tree/master/data/consoleAPICall/console-trace)
- [Integration point](https://dxr.mozilla.org/mozilla-central/source/devtools/client/webconsole/webconsole.js#1284)

### PR DESCRIPTION
**Pull request by nchevobbe**
Show stacktrace using StackTrace React component
Added a CSS rule for `open` stacktrace (class instead of attribute)
There's no test ( @linclark said it could land without them for now https://github.com/devtools-html/gecko-dev/issues/66#issuecomment-236186288)

Fixes #66

### CODE REVIEW

**Comment by nchevobbe** [comment]
@linclark, @bgrins I think this is ready for review

**Comment by linclark** [comment]
I tested this out... so cool!

Unfortunately it looks like there might have been a very tiny issue with the rebase here. I think the best thing to do in this case is this...

Backup this branch by renaming it:

```
git branch -M trace trace-bu
```

Then, checkout the latest `console-frontend`

```
git fetch <remote name>
git checkout -b trace <remote-name>/console-frontend
```

Then cherry-pick your commit on top:

```
git cherry-pick trace-bu~0
```

You'll get a message that you need to resolve the conflicts. It's a very simple conflict, so should be easy to resolve.

**Comment by linclark** [comment]
Once you've resolved that, try running the npm tests. I have instructions in the new README for that.

```
Error: Cannot find module 'chrome'
```

The error that you'll get is one I've seen before. The way I resolved it was making it possible to mock Services and l10n. Then in the test, I just use the mock versions.

In this case, it's likely something in the StackTrace component. I haven't had a chance to dig in, but I wouldn't be surprised if it was the `LocalizationHelper`.

**Comment by nchevobbe** [comment]
> You'll get a message that you need to resolve the conflicts. It's a very simple conflict, so should be easy to resolve.

Thanks for the guidance, all went well.

**Comment by linclark** [comment]
Excellent!

I was thinking about the error more. I think the best solution might be to set up dependency injection using the store. Basically, we'd have a `services` reducer. We'd move the the prefs service and the l10n service to that. Those would be passed in when we create the store. Then any consuming components in new-console-frontend could pull them from the store. In the tests, we'd alter `setupStore` to pass in the mock versions when it's instantiating the store.

StackTrace would require some special handling since it's being used outside of new-console-frontend (where we aren't using Redux). We'd have to change that so it accepted the l10n service as a prop.

I think this should work well, but let me know if any parts seem weird.

**Comment by nchevobbe** [comment]
I don't know if I will have enough time to look at the test error today and tomorrow, but for now, the commit in this PR is ready for review.

**Comment by linclark** [comment]
Just talked this over with @bgrins and I think we came up with a good strategy for it. We're planning to use the require-hacker that I just added to the tests. That means that whenever it tries to load something that depends on something chrome privileged, it will just load one of our mocks instead.

I created #186 to track this. We should wait for that to land before landing this one so we don't break `npm test`.

**Comment by nchevobbe** [comment]
I fetched and rebased to have https://github.com/devtools-html/gecko-dev/issues/188 .
I added a commit with the stacktrace property in the stub.

**Comment by linclark** [comment]
nice!!

I had to resolve a conflict with Brian's test PR, so this landed as 8656b5f3ab

**Pull request closed without merging**
