### PR TITLE
Add LocalizationHelper to mocks

### PR DESCRIPTION
**Pull request by linclark**
r? @nchevobbe 

If you cherry-pick this PR, then you should be able to get tests to run in yours. Then all you need to do is add `stacktrace: undefined` to the `"console.log('foobar', 'test')"` entry in `stubs.js`.

I'll be working on automating the updates of these (so that any changes to prepareMessages are automatically reflected in them) in #169

### CODE REVIEW

**Comment by nchevobbe** [comment]
@linclark it looks like there's a small mistake in WebConsoleUtils.js :

`const L10n = require("devtools/client/webconsole/new-console-output/test/fixtures/l10n");`

`l10n` must be changed to `L10n` (with a capital L) 

I still have errors after that : 

```
/Users/nicolaschevobbe/Projects/gecko-dev/devtools/client/shared/components/stack-trace.js:8
const { DOM: dom, createClass, createFactory, PropTypes } = React;
      ^

SyntaxError: Unexpected token {
```

Is there some problem with this syntax ?

**Comment by linclark** [comment]
There shouldn't be any problem with that syntax. I didn't get that error when testing on your PR, so that's weird.

**Comment by linclark** [comment]
I wonder if the syntax issue is something going on with a babel dependency. Maybe try `rm -r node_modules; npm cache clear; npm i`

**Comment by nchevobbe** [comment]
@linclark seems to work for me now (after upgrading to latest node version) : 

```
  Filter actions:
    filterTextSet
      ✓ creates expected action
    filterToggle
      ✓ creates expected action
    filtersClear
      ✓ creates expected action

  Message actions:
    messageAdd
      ✓ creates expected action given a packet (55ms)
    messagesClear
      ✓ creates expected action

  UI actions:
    filterBarToggle
      ✓ creates expected action

  ConsoleAPICall component:
    console.log
Warning: Failed propType: Required prop `onViewSourceInDebugger` was not specified in `ConsoleApiCall`.
Warning: Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <span>. See https://fb.me/react-warning-keys for more information.
Warning: Failed propType: Invalid prop `grip` of type `string` supplied to `GripMessageBody`, expected `object`. Check the render method of `ConsoleApiCall`.
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ConsoleApiCall`. See https://fb.me/react-warning-keys for more information.
      ✓ renders string grips (68ms)
      ✓ renders repeat node
    console.count
      ✓ renders

  EvaluationResult component:
Warning: Failed propType: VariablesViewLink: prop type `object` is invalid; it must be a function, usually from React.PropTypes. Check the render method of `Date`.
    ✓ renders a grip result

  FilterBar component:
Warning: React.renderToStaticMarkup is deprecated. Please use ReactDOMServer.renderToStaticMarkup from require('react-dom/server') instead.
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `FilterBar`. See https://fb.me/react-warning-keys for more information.
    ✓ initial render
    ✓ displays filter bar when button is clicked (57ms)
    ✓ fires MESSAGES_CLEAR action when clear button is clicked (381ms)
    ✓ sets filter text when text is typed

  FilterButton component:
    ✓ displays as active when turned on
    ✓ displays as inactive when turned off
    ✓ fires FILTER_TOGGLE action when clicked

  MessageContainer component:

Warning: Failed propType: Required prop `onViewSourceInDebugger` was not specified in `MessageContainer`.
    ✓ pipes data to children as expected
    ✓ picks correct child component

  MessageIcon component:
    ✓ renders icon based on severity

  PageError component:
    ✓ renders a page error

  MessageRepeat component:
    ✓ renders repeated value correctly
    ✓ renders an un-repeated value correctly

  Filtering
    Severity filter
      ✓ filters log messages
      ✓ filters debug messages
      - filters info messages
      ✓ filters warning messages
      ✓ filters error messages
    Text filter
      ✓ matches on value grips
    Combined filters
      - filters

  Clear filters
    ✓ clears all filters

  Message reducer:
    ✓ adds a message to an empty store
    ✓ increments repeat on a repeating message
    ✓ does not clobber a unique message
    ✓ clears the store in response to console.clear()
    ✓ limits the number of messages displayed (191ms)

  getRepeatId:
    ✓ returns same repeatId for duplicate values
    ✓ returns different repeatIds for different values
    ✓ returns different repeatIds for different severities
    ✓ handles falsy values distinctly


  38 passing (2s)
  2 pending
```

**Pull request merged**
