### PR TITLE
Fix broken console messages

### LINKED ISSUE #102: Some messages make the console break completely
We should make sure this doesn't happen.

### PR DESCRIPTION
**Pull request by linclark**
Fix #102 
## Testing instructions

Go to https://www.facebook.com/ with the console open

Before: You would not be able to console.log() anything because of an error in the PageError and console messages
After: console.log() works after page is loaded

### CODE REVIEW

**Comment by linclark** [comment]
@bgrins this is ready for review

**Comment by bgrins** [comment]
@linclark looks like this has 8 commits in it - maybe related to a rebase?

**Comment by linclark** [comment]
@bgrins yeah, I probably put this one up and then rebased+pushed the console-frontend branch afterward, so it was counting all of the commits that had been merged over there. I rebased this branch off of that so now it just has the 1 relevant commit.

**Comment by bgrins** [comment]
Nice, fixes the problem for me

**Pull request merged**
