### PR TITLE
Fix CSS for the FilterBar. r=@linclark, @ntim, @helenvholmes

### PR DESCRIPTION
**Pull request by nchevobbe**
@helenvholmes , @ntim does this look good for you ?

search
search_not_empty

### CODE REVIEW

**Comment by linclark** [comment]
This looks good to me. Will wait a day to see if @helenvholmes or @ntim have input. If there's no additional changes by then, will land this.

**Comment by nt1m** [comment]
@ntim, don't mind the ping, it's supposed to be for me (oh, I want your username btw :) )

Anyway, @nchevobbe, looks good to me: r+

**Comment by ntim** [comment]
@nt1m haha, already figured.

**Comment by linclark** [comment]
Thanks!

**Pull request merged**
