### PR TITLE
Use require-hacker to load mocks in npm tests

### LINKED ISSUE #186: Use require-hacker to load mocks in npm tests
There are still some chrome privileged things like `Services` and `LocalizationHelper`. These break the mocha tests.

There is currently work going on in the devtools.html effort to de-chrome these. Until that happens, we can use the `require-hacker` to load mock versions in tests.

### PR DESCRIPTION
**Pull request by linclark**
Fixes #186 

This depends on #187
## Testing instructions
1. `npm i` to update `mocha-test-require-hacker`
2. `npm test`... no whammies

### CODE REVIEW

**Comment by linclark** [comment]
@bgrins this is ready and will be necessary for the test fix for #184

**Comment by linclark** [comment]
@bgrins this is ready

**Comment by bgrins** [comment]
Looks good to me

**Comment by bgrins** [comment]
We can now delete https://github.com/devtools-html/mocha-test-require-hacker too

**Comment by linclark** [comment]
Thanks for the review. Other repo deleted

**Pull request merged**
